from pygame.math import Vector2
import pygame

# screen
SCREEN_WIDTH_DEFAULT = 1280
SCREEN_HEIGHT_DEFAULT = 720
TILE_SIZE = 48

# direction
DIRECTION_LEFT = "left"
DIRECTION_RIGHT = "right"
DIRECTION_DOWN = "down"
DIRECTION_UP = "up"

DIRECTION_DIAGONAL_LEFT_DOWN = "diagonal left down"
DIRECTION_DIAGONAL_LEFT_UP = "diagonal left up"
DIRECTION_DIAGONAL_RIGHT_DOWN = "diagonal right down"
DIRECTION_DIAGONAL_RIGHT_UP = "diagonal right up"

# overlay
OVERLAY_TOOL = "tool"
OVERLAY_ENTITY = "entity"
ITEM_INVENTORY = "item inventory"
OVERLAY_LEADERBOARD = "leader board"

OVERLAY_TOOL_DISTANCE = 75
OVERLAY_ENTITY_DISTANCE = 75

USE_TOOL_OFFSET = {
    DIRECTION_LEFT: Vector2(-70, 0),
    DIRECTION_RIGHT: Vector2(70, 0),
    DIRECTION_UP: Vector2(0, -70),
    DIRECTION_DOWN: Vector2(0, 70),
    DIRECTION_DIAGONAL_LEFT_DOWN: Vector2(-55, 55),
    DIRECTION_DIAGONAL_LEFT_UP: Vector2(-55, -55),
    DIRECTION_DIAGONAL_RIGHT_DOWN: Vector2(55, 55),
    DIRECTION_DIAGONAL_RIGHT_UP: Vector2(55, -55),
}

LAYER_GROUND = "Ground"
LAYER_PLAYER = "Player"
LAYER_ZOMBIE = "Zombie"
LAYER_STONE = "Stones"
LAYER_TREE = "Trees"
LAYER_ENTITY_BASE = "Entity Base"
LAYER_ENTITY_HEAD = "Entity Head"
LAYER_ENTITY_PROJECTILE = "Entity Projectile"
LAYER_MAIN = "Main"
LAYER_MAX_HEALTH = "Health Bar"
LAYER_HEALTH = "Main"
LAYER_UPGRADE = "Upgrade"
LAYER_BUTTON = "Button"
LAYER_TEXT = "Text"


LAYERS = {
    LAYER_GROUND: 0,
    LAYER_STONE: 1,
    LAYER_TREE: 2,
    LAYER_PLAYER: 3,
    LAYER_ZOMBIE: 4,
    LAYER_ENTITY_BASE: 5,
    LAYER_ENTITY_HEAD: 6,
    LAYER_ENTITY_PROJECTILE: 7,
    LAYER_MAX_HEALTH: 8,
    LAYER_HEALTH: 9,
    LAYER_UPGRADE: 10,
    LAYER_BUTTON: 11,
    LAYER_TEXT: 12,
    LAYER_MAIN: 13,
}
